# choose which model to use {tf : Transformer (BERT-like) / snrm : SNRM}
model: 'snrm'
vocab_size: 30522
batch_size: 64
lr: 0.0001
MaxMRRRank: 1000
max_input_len: 150
stopwords: "none"
remove_unk: False
patience: 2
eval_every: 5000
sparse_dimensions: 1000
large_out_biases: False
num_workers: 0
bottleneck_run: False
tf:
  hidden_size: 256
  num_of_layers: 2
  num_attention_heads: 4
  input_length_limit: 150
  # the method that the hidden states over all sequence steps are being aggregated {CLS, AVG, MAX}
  pooling_method: 'CLS'
  last_layer_norm: True
  act_func: "relu"
snrm:
  hidden_sizes: '200' # for multiple layers add '-' between hidden sizes  eg. ('100-400-200')
  n: 5
  dropout_p: 0.2
  n_gram_model: "cnn" # cnn or bert, defining the way that the n gram is being aggregated
  embedding_dim: 768
debug: False
max_rank: 1000
experiments_dir: "experiments"
temp_exp_prefix: "Dev..."
max_candidates_per_posting_list: -1
num_epochs: 100
num_of_workers_index: 7
l1_scalar: 0.0
num_of_decimals: 5
balance_scalar: 0.0
disable_cuda: False
data_path: "data/"
embedding: 'bert'
metric: "mrr"
glove_embedding_path: '${data_path}/embeddings/glove.6B.300d.p'
glove_word2idx_path: '${data_path}/embeddings/glove.6B.300d_word2idx_dict.p'
query_file_val: '${data_path}/msmarco/msmarco-test2019-queries_43.${embedding}.tsv'
docs_file_val: '${data_path}/msmarco/msmarco-passagetest2019-top1000_43.${embedding}.tsv'
qrels_val: '${data_path}/msmarco/2019qrels-pass_filtered_ms_marco.txt'
docs_file_train: '${data_path}/msmarco/collection.${embedding}.tsv'
query_file_train: '${data_path}/msmarco/queries.train.${embedding}.tsv'
triplets_file_train: '${data_path}/msmarco/qidpidtriples.train.full.tsv'
robust_ranking_results_file: '${data_path}/robust04/run.robust04.bm25.topics.robust04.301-450.601-700.txt'
robust_docs_file: '${data_path}/robust04/robust04_raw_docs.num_query_glove_stop_none_remove_unk.tsv'
robust_query_file: '${data_path}/robust04/04.testset_num_query_lower_glove_stop_none_remove_unk.tsv'
robust_qrel_test: '{data_path}/robust04/qrels.robust2004.txt'
sampler: 'random'
target: 'binary'
top_k_per_query: -1
dataset: 'msmarco'
# debug_str = '' if not debug else '.debug'
# triplets_fname = f'{dataset_path}/msmarco/qidpidtriples.train.full{debug_str}.tsv'
# documents_path = f'{dataset_path}/msmarco/collection.tokenized.tsv'
# queries_path = f'{dataset_path}/msmarco/queries.train.tokenized.tsv'
